theme = "minimo"
baseURL = "https://mlr-web.netlify.com/"
languageCode = "en-us"
title = "mlr-org"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

enableEmoji = true
hasCJKLanguage = true

disqusShortname = "mlr-org-blog"

disable_mathjax = false

[params]
  sitename = "mlr: Machine learning in R"

[[menu.main]]
    name = "Home"
    url = "https://mlr-web.netlify.com/"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/mlr-org"
    weight = 2
[[menu.main]]
    name = "Authors"
    url = "https://github.com/mlr-org/mlr/wiki/Misc#mlr-developer-team-and-contributors-page"
    weight = 3
[[menu.main]]
    name = "Docs"
    url = "https://mlr-org.github.io/mlr/"
    weight = 4
[[menu.main]]
    name = "Stackoverflow"
    url = "https://stackoverflow.com/questions/tagged/mlr"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 6
